### PR TITLE
Fix some formatting issues I somehow missed

### PR DESCRIPTION
**Pull request by bdpedigo**

### CODE REVIEW

**Comment by bdpedigo** [comment]
@dwaynepryce it looks like `code-format-check (pull_request_target)` is failing because of the exact issue im trying to fix here... just want to check if that makes sense to you?

**Comment by dwaynepryce** [comment]
Yeah, I'm trying to figure out why.  The implication was that it was going to check out from your branch, but use our local workflow, but it LOOKS like it's only checking out from local and running it - which defeats the entire purpose.  Ugh.

**Comment by dwaynepryce** [comment]
Ugh that "fix" for "we can't get our build to run for forked PRs" didn't do what we expected.  I'm going to let this merge in even though the pull request target one is failing because the whole thing is screwed up.

**Comment by dwaynepryce** [comment]
The reason why the build was failing was because `pull_request_target` event actually triggers a build of our target branch - dev.  Not the place that actually asked us to do the build.

In general that doesn't work the way I expected, so I am going to disable it for now going forward and we'll figure out a different workaround for the NDD group

**Pull request merged**
