### PR TITLE
Fix incorrect use of optimal transport params in Seedless Procrustes

### PR DESCRIPTION
**Pull request by bdpedigo**
- [ ] Does this PR add any new dependencies?
- [ ] Does this PR modify any existing APIs?
   - [ ] Is the change to the API backwards compatible?
- [ ] Have you built the documentation (reference and/or tutorial) and verified the generated documentation is appropriate?

#### Reference Issues/PRs
None

#### What does this implement/fix? Briefly explain your changes.
Fixes a bug (I think?) where the wrong parameter was used in sinkhorn. 
I haven't tested the effects of this much - but seems like they could be huge if eps is less than one. My guess is SeedlessProcrustes would always terminate after one iteration or something like that with the old code

#### Any other comments?
cc @tliu68 who found this issue
cc @alyakin314 who may have thoughts

### CODE REVIEW

**Review by alyakin314 — APPROVED** [review]
looks fine. 

my apologies for the slip.

**Comment by alyakin314** [comment]
i was able to trace it to here:

https://github.com/PythonOT/POT/blob/f6139428e70ce964de3bef703ef13aa701a83620/ot/bregman.py#L388

(they import sinkhorn from ot.bergman, and that is a wrapper for sinkhorn_knopp)

so my guess is that it indeed was only doing one iteration.

**Comment by alyakin314** [comment]
yet simultaneously i find it somewhat hard to believe.

**Comment by bdpedigo** [comment]
> yet simultaneously i find it somewhat hard to believe.

same, yet seems like this would matter for at least a few papers. and some stuff ive been doing now. also possible that 1 iteration is pretty good most of the time

**Comment by bdpedigo** [comment]
@j1c i wonder if this matters for improved nonpar paper, just a heads up

**Comment by alyakin314** [comment]
> > yet simultaneously i find it somewhat hard to believe.
> 
> same, yet seems like this would matter for at least a few papers. and some stuff ive been doing now. also possible that 1 iteration is pretty good most of the time

paper-wise i can only think of Jaewon's. I haven't used it in mine, and Agterbreg was using his R implementation. I've played with a very few global iterations (it worked okay) but never with OT iterations.

**Pull request merged**
