### PR TITLE
suppressed warnings in mcc tutorial

### LINKED ISSUE #631: [BUG] giant series of runtime warnings in MCC tutorial
https://graspy.neurodata.io/tutorials/connectomics/mcc.html
see [11]

### PR DESCRIPTION
**Pull request by rajpratyush**
#### Reference Issues/PRs
closes #631

### CODE REVIEW

**Comment by bdpedigo** [comment]
hi @rajpratyush thanks for the PR, a couple of comments here
- my feedback on the other PR was just to make the warning filter specific to the actual warning that we were seeing. You can look up how to use the warnings library to filter for specific warnings, I think from specific packages and/or with specific names.
- Jupyter notebooks need to be cleared of all output before being committed, as this will cause them to be run and built automatically each time our documentation builds. I'm not sure how you like to run jupyter notebooks but in the web-based version I know there is a "clear all cells" option or something like that.

**Comment by rajpratyush** [comment]
@bdpedigo I could not understand the  the first point clearly I made the warning filter specific to a particular cell that was showing a lot of warnings as I had ran it before suppressing the warnings and found that code cell number 11 was putting out a lot of warnings so I tweaked the code cell itself to suppress all the warnings or do you want me to suppress only a particular type of warning. Please clarify

**Comment by bdpedigo** [comment]
> so I tweaked the code cell itself to suppress all the warnings or do you want me to suppress only a particular type of warning.

We'd like to only suppress the specific type of warning that was being thrown multiple times in that cell:

```pytb
/opt/hostedtoolcache/Python/3.8.7/x64/lib/python3.8/site-packages/hyppo/_utils.py:67: RuntimeWarning: The number of replications is low (under 1000), and p-value calculations may be unreliable. Use the p-value result, with caution!
  warnings.warn(msg, RuntimeWarning)
```

I think you can filter by library (hyppo) and type (RuntimeWarning) and probably other things too, but in general i just want to filter out only that specific warning.

**Comment by rajpratyush** [comment]
@bdpedigo can you review #663

**Comment by bdpedigo** [comment]
@rajpratyush are you closing this PR then? 

As a reminder, it is much easier for everyone if you update an open PR after receiving feedback rather than creating a brand new PR each time.

**Comment by rajpratyush** [comment]
actually this was done on a new branch and I still haven't got much deep practice of git CLI

**Pull request closed without merging**
