### PR TITLE
renamed sbm

### LINKED ISSUE #524: can import sbm from two different places
`from graspologic.models import sbm`
`from graspologic.simulations import sbm`

Both of these work. when we get sbm from simulations, it's (correctly) the function, but when we get it from models, it's the sbm module. This is confusing to a new user I think

### PR DESCRIPTION
**Pull request by rajpratyush**
- [ ] Does this PR add any new dependencies?
- [ ] Does this PR modify any existing APIs?
   - [ ] Is the change to the API backwards compatible?
- [ ] Have you built the documentation (reference and/or tutorial) and verified the generated documentation is appropriate?

#### Reference Issues/PRs

closes #524 
#### What does this implement/fix? Briefly explain your changes.
 renamed the sbm.py in graspologic/models which the SBM estimator module

### CODE REVIEW

**Comment by loftusa** [comment]
All looks good to me, just briefly went through in vscode and doesn't look like you missed anything!

**Comment by bdpedigo** [comment]
@loftusa a test is failing

**Comment by rajpratyush** [comment]
Which one @bdpedigo

**Comment by loftusa** [comment]
@rajpratyush look at the "some checks were not successful" above "merge pull request" and scroll down to the failing unit-and-doc-test, then click "details"

Some weird `tkinter` test fail in only windows with python3.6...
```
FAILED tests/test_plot_matrix.py::test_matrix_output - _tkinter.TclError: Can...
```

**Comment by rajpratyush** [comment]
@loftusa actually I am working in windows environment.

**Comment by loftusa** [comment]
@rajpratyush
> and yes my system lacks tkinter

I don't think this is the issue. The tests run on a remote server which auto-installs everything into a virtual environment prior to running, so they wouldn't use anything on your system. 

It looks like Tkinter wasn't installed properly on this particular test instance, which is a pretty weird error. I'm not too familiar with exactly how the test instances are getting setup these days... @dwaynepryce got any thoughts on this one?

**Comment by rajpratyush** [comment]
@loftusa yess but i couldnot find any article on installing tkinter on python 3.6.

Maybe that's why it is failing

**Comment by dwaynepryce** [comment]
Whatever happened to the windows images used in the time since you had the problem and now seems to have been fixed?

> It looks like Tkinter wasn't installed properly on this particular test instance, which is a pretty weird error. I'm not too familiar with exactly how the test instances are getting setup these days... @dwaynepryce got any thoughts on this one?

We tell github actions we want to make a matrix from windows, mac, and linux across 3.6, 3.7, and 3.8.  we don't install anything onto these systems besides our pip requirements.  It's nothing crazy... but we seem to have had a temporary issue?  And it's gone now?

**Comment by loftusa** [comment]
> Whatever happened to the windows images used in the time since you had the problem and now seems to have been fixed?
> 
> > It looks like Tkinter wasn't installed properly on this particular test instance, which is a pretty weird error. I'm not too familiar with exactly how the test instances are getting setup these days... @dwaynepryce got any thoughts on this one?
> 
> We tell github actions we want to make a matrix from windows, mac, and linux across 3.6, 3.7, and 3.8. we don't install anything onto these systems besides our pip requirements. It's nothing crazy... but we seem to have had a temporary issue? And it's gone now?

I guess? It does certainly appear to be gone. It was a really weird error, ONE of the build tests was failing, and it was only on windows python 3.6, and it had something to do with tkinter failing in some way.

but it's fixed now? so I guess we're happy??

**Comment by dwaynepryce** [comment]
without having 100% control over the build server image we're not really going to know.  if it keeps happening we'll actually likely have to escalate with github to find out what's up (unless we can get consistent failures or something)

**Pull request merged**
