### PR TITLE
Leiden types wrapper bugfix

### LINKED ISSUE #738: [BUG] Using layout_umap and getting key error
## Expected Behavior
a graph layout using UMAP for dim reduction to 2d

## Actual Behavior
coming from layouts\auto.py
 KeyError: '2'

## Example Code
Please see [How to create a Minimal, Reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) for some guidance on creating the best possible example of the problem
```python
import networkx as nx
from graspologic.layouts import layout_umap

g = nx.erdos_renyi_graph(10, 0.7, directed=False)
layout_umap(g)
```

## Full Traceback
```pytb
Paste the full traceback in case there is an exception

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-17-1c062a6ca19a> in <module>
      3 
      4 g = nx.erdos_renyi_graph(10, 0.7, directed=False)
----> 5 layout_umap(g)

~\miniconda3\lib\site-packages\graspologic\layouts\auto.py in layout_umap(graph, min_dist, n_neighbors, max_edges, random_seed)
    177         min_dist=min_dist, n_neighbors=n_neighbors, random_state=random_seed
    178     ).fit_transform(tensors)
--> 179     positions = _node_positions_from(lcc_graph, labels, points, random_seed=random_seed)
    180     return lcc_graph, positions
    181 

~\miniconda3\lib\site-packages\graspologic\layouts\auto.py in _node_positions_from(graph, labels, down_projection_2d, random_seed)
    241     scaled_points = _scale_points(down_projection_2d, covered_area)
    242     partitions = leiden(graph, random_seed=random_seed)
--> 243     positions = [
    244         NodePosition(
    245             node_id=key,

~\miniconda3\lib\site-packages\graspologic\layouts\auto.py in <listcomp>(.0)
    246             x=scaled_points[index][0],
    247             y=scaled_points[index][1],
--> 248             size=sizes[key],
    249             community=partitions[key],
    250         )

KeyError: '2'

```

## Your Environment
* Python version:  3.8
* graspologic version:

### PR DESCRIPTION
**Pull request by dwaynepryce**
- [ ] Does this PR add any new dependencies?
- [x] Does this PR modify any existing APIs?
   - [ ] Is the change to the API backwards compatible?
- [x] Have you built the documentation (reference and/or tutorial) and verified the generated documentation is appropriate?

#### Reference Issues/PRs

Partially fixes #738

#### What does this implement/fix? Briefly explain your changes.
When running Leiden, if your graph has `int` (or anything other than `str`) node IDs, we automatically convert them to string representations for the native leiden impl to handle.  The problem is that the node id -> partition dictionary we return uses the `str` representation as the key, which won't map up to the value you actually provided in your networkx Graph.

This definitively fixes the bug in Leiden - which was one of the issues we had in #738!

The problem is that 738 also has a bug almost the same in n2v - namely, that the nodes are converted to strings for word2vec to operate over them, then returned as string labels.  We fixed the first problem, but not the second - yet.  @nyecarr is working on a n2v refactor that will fix this, and thus fully close #738.

In the meantime, this should solve Leiden over our graphs.  ~~I just realized I also need to create a test to validate it works over matrices as well as networkx - so I'll make sure that works in a test prior to actually completing this PR.~~ This is done now

#### Any other comments?

It's unclear to me that we need a new minor release with a breaking API change if we haven't actually published a final release of 0.2.0 yet.  Our dev / prerelease versions will certainly have a breaking api change, but ... I don't think this needs to become 0.3.0?  @bdpedigo?

### CODE REVIEW

**Comment by bdpedigo** [comment]
> It's unclear to me that we need a new minor release with a breaking API change if we haven't actually published a final release of 0.2.0 yet. Our dev / prerelease versions will certainly have a breaking api change, but ... I don't think this needs to become 0.3.0? @bdpedigo?

Agree w/ you personally, prerelease seems like buyer beware to me :)

**Comment by bdpedigo** [comment]
P.S. kinda unrelated but i've come across a bunch of node2vec implementations in other libraries, like
https://karateclub.readthedocs.io/en/latest/modules/root.html#karateclub.node_embedding.neighbourhood.node2vec.Node2Vec
or https://stellargraph.readthedocs.io/en/stable/api.html#node2vec. 

Just wondering about thoughts on calling these libraries - in our continuing quest to push stuff out of graspologic as it makes sense.

**Comment by dwaynepryce** [comment]
> P.S. kinda unrelated but i've come across a bunch of node2vec implementations in other libraries, like
> https://karateclub.readthedocs.io/en/latest/modules/root.html#karateclub.node_embedding.neighbourhood.node2vec.Node2Vec
> or https://stellargraph.readthedocs.io/en/stable/api.html#node2vec.
> 
> Just wondering about thoughts on calling these libraries - in our continuing quest to push stuff out of graspologic as it makes sense.

So, I'm for it, caveat ergonomics - and having built enough stellargraphs, I don't _love_ their API.  One thing we did with topologic is try to at least provide a smooth api for everyone to use _underlying library_ - the idea being that you don't need to know networkx or numpy or scipy or whatever, you can just come to our one-stop-graph-processing-shop for all your graph processing needs.

I am keenly in favor of moving _novel_ tech out of graspologic and "upstream".  But that just means we still will likely have to write a wrapper to use it once the landing spot for it picks it up and morphs it over to their own project's API paradigm.

In summation: "sure, maybe, but we still have to have a n2v entry point in graspologic".  It'd be the same when/if ASE/LSE graduate too!

**Comment by bdpedigo** [comment]
> In summation: "sure, maybe, but we still have to have a n2v entry point in graspologic". It'd be the same when/if ASE/LSE graduate too!

yeah I anticipated we'd probably want a wrapper regardless, sounds good!

**Review by Nyecarr — APPROVED** [review]

**Pull request merged**
