### PR TITLE
reformat gmm.covariances_ in pairplot_with_gmm

### PR DESCRIPTION
**Pull request by tliu68**
#### Reference Issues/PRs 
PR#541

#### What does this implement/fix? Briefly explain your changes.
Adds code to format `gmm.covariances_` in `pairplot_with_gmm` to enable plotting of ellipses for GM models with all covariance types.

### CODE REVIEW

**Comment by bdpedigo** [comment]
@tliu68 mind adding a super short test showing that this works (does not error) with each of the 4 types on some tiny data? Otherwise I'm ready to merge!

**Comment by tliu68** [comment]
@bdpedigo Hey! I added some simple tests. And I also realized that the part of adding a title didn't work, so I made a tiny change. Since it's very trivial, I didn't make a new PR.

**Review by bdpedigo — APPROVED** [review]

**Comment by bdpedigo** [comment]
thanks for the pr, @tliu68!

**Comment by bdpedigo** [comment]
@tliu68 looks like some checks broke, not sure what happened here, but is preventing a merge

**Comment by tliu68** [comment]
> @tliu68 looks like some checks broke, not sure what happened here, but is preventing a merge

It seems to be related to this [PR](https://github.com/microsoft/graspologic/pull/644/checks?check_run_id=1780631791)? There was a code-formatting error.

**Comment by bdpedigo** [comment]
if you black all files does it fix it (for the purposes of this PR)?

**Comment by bdpedigo** [comment]
@tliu68 just merge in #649 once it gets merged and then should be good to go, thanks for tracking that down

**Pull request merged**
