### PR TITLE
Add sparse matrix support for some matrix plotting functions

### PR DESCRIPTION
**Pull request by bdpedigo**
- [ ] Does this PR add any new dependencies?
- [x] Does this PR modify any existing APIs?
   - [x] Is the change to the API backwards compatible?
- [ ] Have you built the documentation (reference and/or tutorial) and verified the generated documentation is appropriate?

#### Reference Issues/PRs
None

#### What does this implement/fix? Briefly explain your changes.
- Allows the user to pass sparse matrices to `adjplot` and `matrixplot` when using the `scattermap` option

#### Any other comments?
- Could absolutely have a conversation about the best API for these functions. I'm not currently that happy with it, but don't want to let that hold up this PR.

### CODE REVIEW

**Comment by bdpedigo** [comment]
TODO:
- [ ] Update documentation
- [ ] Add type hinting
- [ ] Add a test

**Comment by bdpedigo** [comment]
@nyecarr any chance you'd be willing to have a look at this since we were just talking about it?

**Comment by bdpedigo** [comment]
@asaadeldin11 any chance you could take a quick look at this?

**Review by asaadeldin11 — APPROVED** [review]
Looks good to me @bdpedigo .

**Comment by bdpedigo** [comment]
thanks @asaadeldin11 !

**Pull request merged**
