### PR TITLE
Signal Subgraph Screening, Coherence

### LINKED ISSUE #120: signal subgraph
there are now 3 papers that due "signal subgraph"

- https://arxiv.org/abs/1804.09567
- https://arxiv.org/abs/1108.1427
- https://arxiv.org/abs/1801.07683v1

let's have at least some way of doing it here.

### LINKED ISSUE #305: add signal subgraph to docs, fix line lengths, add demo

### PR DESCRIPTION
**Pull request by CaseyWeiner**
#### Reference Issues/PRs
Fixes #120 
Fixes #305 
Addresses part of #461 

#### What does this implement/fix? Explain your changes.
Cleans up subgraph documentation, renames sg module and cleans up subgraph folder. Adds two new subgraph screening algorithms with associated tutorial notebooks, unit tests, and documentation changes.

#### Any other comments?
Proof nb [here](https://nbviewer.jupyter.org/github/NeuroDataDesign/team_graphstats1/blob/master/Casey/SS/Subgraph_Proof_Notebook.ipynb)

### CODE REVIEW

**Comment by caseypw** [comment]
Do the checks normally take this long @dwaynepryce @bdpedigo ? I am wondering if I messed up something

**Comment by dwaynepryce** [comment]
@caseypw - not you!

The checks aren't running on forks for some dumb reason.  Can you enable github actions on your fork (go to your forked project, go up to the top menu where it says actions, enable them) as well as merge `dev` back in to your fork so you're trying to merge with the latest we have?  I'll validate that your fork is building successfully with no changes to the CI file and if everything is successful we can merge this back in.

**Comment by caseypw** [comment]
That seemed to have done the trick! Thank you @dwaynepryce !
It seems to have failed the mypy check, is that because we haven't yet added typing to all the modules?

**Comment by caseypw** [comment]
Do you have time available to review this PR @j1c ?

**Comment by j1c** [comment]
Sure, but prob wont get to it till the end of the week.

**Comment by caseypw** [comment]
> 
> 
> Sure, but prob wont get to it till the end of the week.

Thank you

**Comment by caseypw** [comment]
@j1c Did you get a chance to review?

**Comment by bdpedigo** [comment]
closing as out of date, if there is an author and reviewer who wants to take this on feel free to reopen

**Pull request closed without merging**
