### PR TITLE
LSE-OMNI

### LINKED ISSUE #550: Add LSE-OMNI
Should be able to run OMNI where each individual matrix that is input is the Laplacian of each.

Theory/papers on it have not been published (to my knowledge) but has definitely been used successfully in the wild.

Maybe we want to include R-LSE as an option?

### PR DESCRIPTION
**Pull request by zeou1**
[] Does this add any new dependencies?
[] Does this modify any existing APIs?
[] Is the change to the API backwards compatible?
[] Have you built the documentation (reference and/or tutorial) and verified the document generated is appropriate?

#### What does this implement/fix? Briefly explain your changes.
Fixes #550. 
This PR adds LSE-OMNI by adding a `_get_laplacian_matrices` helper function and a `lse` parameter. Users can set the `lse` parameter to `True` to use LSE-OMNI instead of ASE-OMNI.
#### Any other comments?
I am still making edits to the notebook, that will come up shortly afterwards.

### CODE REVIEW

**Comment by Jingyan230** [comment]
## Peer review checklist

### PR itself (on GitHub)
- [x] PR has a descriptive and succinct title.
- [ ] PR has a _brief_ description of what was changed.
- _Maybe make a comment about the added comparison section between ASE and OMNI in the OMNI tutorial notebook._
- [x] PR cites any related issues in the PR description (if applicable) and uses [closing keywords](https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) for any issues that should be closed as a result of the PR.
- [x] PR does not have any extraneous file changes associated with it. One common example of an extraneous change is one that was already made in the target branch, but is showing up as part of this PR under `Files changed`.
- [x] PR does not have any unresolved merge conflicts.
- [x] If implementing a major new feature or algorithm, a notebook demonstrating the proof of effectiveness is linked in the PR description. Depending on the feature, this kind of validation may take too long to run as a test or in a tutorial notebook. 

### Style
- [ ] Code follows Python variable naming conventions, one description is [here](https://visualgit.readthedocs.io/en/latest/pages/naming_convention.html). Most variables should be `snake_case` and classes shoud be defined as `UpperCamelCase`, for example.
- _Maybe add full comma to the end of the sentenses for the descriptions in omni.py._
- [x] Code uses descriptive variable names throughout.
- [x] Code has no commented out "junk code."
- [x] Line lengths are short (recommended <88 chars). This includes docstrings. Note:  [black](https://black.readthedocs.io/en/stable/) tries to shorten line lengths but sometimes it is unable to do so automatically, especially for docstrings.

### Documentation
- [x] Any new public classes/functions have docstrings. 
- [x] Any new public classes/functions have been added to the appropriate `.rst` file [here](https://github.com/microsoft/graspologic/tree/dev/docs/reference) to be rendered by `Sphinx`.
- [ ] Any major new features (like a new algorithm) are accompanied by a succinct tutorial notebook. Or, if it is agreed upon with the maintainers that this is out of scope for the current PR, a new issue has been created specifying that we need a tutorial notebook for this functionality.
- _It might be helpful if you could add a brief description in the turorial about the setting and the results of the comparison you did._
- _Is the tutorial of LSE-OMNI included in this PR? If not, it might be helpful to metion that in the comment._
- [x] Any new tutorial notebooks have been added to the appropriate folder [here](https://github.com/microsoft/graspologic/tree/dev/docs/tutorials) and included in the `.rst` file [here](https://github.com/microsoft/graspologic/blob/dev/docs/tutorial.rst) to be rendered by `Sphinx`.
- [ ] Modifications to the documentation render appropriately in the `Netlify` build.
-  _Netlify preview seems to be broken, cannot check the rendered tutorial._

### Testing
- [x] New public classes/functions are tested to ensure they achieve the desired output.
- [x] New public classes/functions are tested to ensure proper errors are thrown when invalid inputs are passed.

**Comment by zeou1** [comment]
@Jingyan230 Can you clarify what you mean by add full comm to the end of sentences?

**Comment by zeou1** [comment]
@bdpedigo do we agree to not have a tutorial section for LSE-OMNI, or what's the best way to present the feature?

**Comment by Jingyan230** [comment]
> @Jingyan230 Can you clarify what you mean by add full comm to the end of sentences?

What I mean is just to add "." in at the end of the sentences.

**Comment by bdpedigo** [comment]
@Nyecarr @dwaynepryce this PR adds back in LSE-OMNI - which I recall people on your side were a fan of? We have not been able to find a simple simulation setting where LSE-OMNI is better than ASE-OMNI (which is not to say that one doesn't exist). I am mainly just wondering:
- whether you have any use cases where LSE-OMNI wins clearly
- whether you have any feedback on this PR in general since you all have likely used LSE-OMNI more than me

**Comment by dwaynepryce** [comment]
> @Nyecarr @dwaynepryce this PR adds back in LSE-OMNI - which I recall people on your side were a fan of? We have not been able to find a simple simulation setting where LSE-OMNI is better than ASE-OMNI (which is not to say that one doesn't exist). I am mainly just wondering:
> 
> * whether you have any use cases where LSE-OMNI wins clearly
> * whether you have any feedback on this PR in general since you all have likely used LSE-OMNI more than me

@JonathanLarson @pbourke - do you guys have any information about LSE Omni for @bdpedigo?  I just know that Jon asked for it repeatedly, but I'm not sure why.  Between you two and @Nyecarr, we should be able to give them some details on how we use LSE Omni and where it fits in.

**Comment by bdpedigo** [comment]
going to close until we have a good example of when to use LSE-omni, but happy to reopen if we find one

**Comment by daxpryce** [comment]
We use lse omni as the foundation for our workgroup fluidity statistic, so we actually do use it.  I finally asked @JonathanLarson point blank because he doesn't respond to github anythings 😠  😛

**Comment by Nyecarr** [comment]
#835

**Pull request closed without merging**
