### PR TITLE
Grammer in line 18.

### PR DESCRIPTION
**Pull request by hugwuoke**
Changing text from a semicolon to a period in line 18. This is a test of my ability to do a pull request with CLA authentication.

### CODE REVIEW

**Review by bdpedigo — APPROVED** [review]
soft approve just to see if github works now

**Comment by bdpedigo** [comment]
(we don't actually need to merge this PR in) 

@hugwuoke @daxpryce looks like this is still broken - @hugwuoke, did the bot never come up for you on this PR asking you to sign again? I just want to make 100% that you've signed the CLA but not sure where to check that on my end

**Comment by daxpryce** [comment]
https://github.com/microsoft/contributorlicenseagreement#commands - can we try those commands again?  I'm wondering if terminating the agreement then agreeing again might fix it?

**Comment by hugwuoke** [comment]
No CLA authentication came up again.

**Comment by daxpryce** [comment]
oh snap nevermind https://github.com/microsoft/ContributorLicenseAgreement/issues/52

let me try to fix this in the admin part of the repo and get back to you

**Comment by daxpryce** [comment]
> oh snap nevermind [microsoft/ContributorLicenseAgreement#52](https://github.com/microsoft/ContributorLicenseAgreement/issues/52)
> 
> let me try to fix this in the admin part of the repo and get back to you

Sweet, that fixed it!  This should work now.

**Comment by bdpedigo** [comment]
awesome, looks mergeable now, thanks a lot @daxpryce! going to close this PR though since it was just a test.

**Pull request closed without merging**
