### PR TITLE
Update issue templates

### LINKED ISSUE #512: add issue templates for enhancements etc.
## Expected Behavior
Templates for enhancement, question etc. Similar to [this](https://github.com/neurodata/hyppo/issues/new/choose)

## Actual Behavior
Default PR template assumes bug fix (as shown here)

## Template Code
```graspologic
Paste the template code (ideally a minimal example) that causes the issue

```

## Full Traceback
```pytb
Paste the full traceback in case there is an exception

```

## Your Environment
* Python version:
* graspologic version:

### PR DESCRIPTION
**Pull request by dwaynepryce**
Closes #512

I don't have any super strong feelings about the feature requests template.

### CODE REVIEW

**Comment by bdpedigo** [comment]
do we want the `config.yml` also? only thing i think it would possibly do for now is whether we want to allow people to make blank issues?

**Comment by bdpedigo** [comment]
related to #531

**Review by bdpedigo — APPROVED** [review]

**Comment by dwaynepryce** [comment]
Still need to remove the old templates and I do want to take a peek at the config.yml from https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser - we'll disable blank issues since these 3 pretty much cover everything.  Unless someone can think of something else!

**Comment by alyakin314** [comment]
feel free to ignore this, but maybe we should be consistent about using `**this text**` vs `## these subtitles` between templates?

**Comment by dwaynepryce** [comment]
@alyakin314 are you saying you don't like headers and prefer just bolding things?  the reason I ask is all the new issue templates use nothing but the various header levels, so there won't be any `**Faux Header**`s floating around anymore

**Comment by alyakin314** [comment]
> @alyakin314 are you saying you don't like headers and prefer just bolding things? the reason I ask is all the new issue templates use nothing but the various header levels, so there won't be any `**Faux Header**`s floating around anymore

@dwaynepryce i was just saying I prefer consistent usage of either.

**Comment by dwaynepryce** [comment]
cool cool - consistency is my jam too!

**Pull request merged**
