### PR TITLE
fixes Move mug2vec to embed module #502

### LINKED ISSUE #502: Move mug2vec to embed module
- [ ] Move this file [`/graspologic/pipeline/mug2vec.py`](https://github.com/microsoft/graspologic/blob/dev/graspologic/pipeline/mug2vec.py) to [`/graspologic/embed/`](https://github.com/microsoft/graspologic/tree/dev/graspologic/embed)
- [ ] Change this from `..embed` to `.embed` once file is moved.
https://github.com/microsoft/graspologic/blob/13577bf3009a6367a385408c252728fab66320fb/graspologic/pipeline/mug2vec.py#L7
- [ ] Remove `/graspologic/pipeline/` folder entirely
- [ ] Add `mug2vec` to imports in the [`/graspologic/embed/__init__.py`](https://github.com/microsoft/graspologic/blob/dev/graspologic/embed/__init__.py) file
- [ ] Change imports from the test file  `graspologic.pipeline` to `graspologic.embed`
https://github.com/microsoft/graspologic/blob/13577bf3009a6367a385408c252728fab66320fb/tests/pipeline/test_mug2vec.py#L9
- [ ] Add the line `.. autoclass:: mug2vec` to the [`/graspologic/docs/reference/embed.rst`](https://github.com/microsoft/graspologic/blob/dev/docs/reference/embed.rst) under `.. autoclass:: MultipleASE`
- [ ] Remove `/graspologic/docs/reference/pipeline.rst` file
- [ ] Remove the line `pipeline` from [`/graspologic/docs/reference/index.rst`](https://github.com/microsoft/graspologic/blob/dev/docs/reference/index.rst)

### PR DESCRIPTION
**Pull request by AnshuTrivedi**
#### Reference Issues/PRs
fixes #502 

#### What does this implement/fix? Explain your changes.
Move mug2vec to embed module
1.   Move file /graspologic/pipeline/mug2vec.py to /graspologic/embed/
2.   Change from ..embed to .embed once file is moved in mug2vec.py
3.  Remove /graspologic/pipeline/ folder entirely
4.  Add mug2vec to imports in the /graspologic/embed/__init__.py file
5.  Change imports from the test file graspologic.pipeline to graspologic.embed in 
     graspologic/tests/pipeline/test_mug2vec.py
6.   Add the line .. autoclass:: mug2vec to the /graspologic/docs/reference/embed.rst under .. autoclass:: MultipleASE
7.   Remove /graspologic/docs/reference/pipeline.rst file
8.  Remove the line pipeline from /graspologic/docs/reference/index.rst

### CODE REVIEW

**Comment by AnshuTrivedi** [comment]
from https://github.com/microsoft/graspologic/blob/13577bf3009a6367a385408c252728fab66320fb/graspologic/__init__.py#L14
remove `import graspologic.pipeline`

Changing this way `..embed import ClassicalMDS, OmnibusEmbed` failing tests and throwing errors. so change it as below
> from .mds import ClassicalMDS
   from .omni import OmnibusEmbed

Almost all tests passed now.

I would love to  hear your feed back and other changes required if any.
Thanks @j1c !

**Comment by alyakin314** [comment]
> Almost all tests passed now.

mypy test failing is okay for now, just fyi.

**Review by alyakin314 — APPROVED** [review]
file changes seem okay to me.

**Comment by alyakin314** [comment]
docs seems to be working as well.

**Comment by j1c** [comment]
> from
> 
> https://github.com/microsoft/graspologic/blob/13577bf3009a6367a385408c252728fab66320fb/graspologic/__init__.py#L14
> 
> 
> remove `import graspologic.pipeline`
> Changing this way `..embed import ClassicalMDS, OmnibusEmbed` failing tests and throwing errors. so change it as below
> 
> > from .mds import ClassicalMDS
> > from .omni import OmnibusEmbed
> 
> Almost all tests passed now.
> 
> I would love to hear your feed back and other changes required if any.
> Thanks @j1c !

Nice catch! Everything looks good, but Im going to ask for one more change, which I originally missed: move `tests/pipeline/test_mug2vec.py` outside the `pipeline` folder to `tests/test_mug2vec.py` and delete the `tests/pipeline/` folder entirely.

Should be good to go after that.

**Comment by AnshuTrivedi** [comment]
@bdpedigo @j1c  I have  made changes suggested and it passed almost all tests except few neutral and optional.
Happy to make more changes if needed.
Thanks !

**Review by j1c — APPROVED** [review]

**Comment by j1c** [comment]
Looks good to me @AnshuTrivedi. Thanks a bunch for the help!

**Pull request merged**
