### PR TITLE
renamed the Sbm.py in models

### LINKED ISSUE #524: can import sbm from two different places
`from graspologic.models import sbm`
`from graspologic.simulations import sbm`

Both of these work. when we get sbm from simulations, it's (correctly) the function, but when we get it from models, it's the sbm module. This is confusing to a new user I think

### PR DESCRIPTION
**Pull request by rajpratyush**
- [ ] Does this PR add any new dependencies?
- [ ] Does this PR modify any existing APIs?
   - [ ] Is the change to the API backwards compatible?
- [ ] Have you built the documentation (reference and/or tutorial) and verified the generated documentation is appropriate?

#### What does this implement/fix? Briefly explain your changes.
closes #524

### CODE REVIEW

**Comment by bdpedigo** [comment]
@loftusa do you mind reviewing when you get a chance?

**Comment by bdpedigo** [comment]
> @loftusa do you mind reviewing when you get a chance?

@loftusa bump

**Comment by dwaynepryce** [comment]
@rajpratyush did you forget to add the replacement to sbm.py?  It is just showing up as deleted.

Also, I think you want to have "clean"/"fresh" cells in your mcc.ipynb file - they have a bunch of your output in them.  If you clear output and save it again after testing it, it should put you in a good state

**Comment by loftusa** [comment]
Basically same comments as @dwaynepryce!

**Comment by rajpratyush** [comment]
I had renamedit it actually to sbm_estimators.py n mcc.ipynb file ig it shows up due to i didnt have the upstream

**Comment by rajpratyush** [comment]
I think probably my master branch has git messed up it will be better if I push a new PR.

**Comment by loftusa** [comment]
> I think probably my master branch has got messed up it will be better if I push a new PR.
> 
> because the issue referring to clearing up of warnings has already been fixed

ok, great, close this one and push a new one?
the other thing that will need to happen with this PR is to go to through the documentation, rest of the code, etc, and make sure that anything that imports using the old name now imports using the new name.

**Comment by rajpratyush** [comment]
Yess surely

**Comment by rajpratyush** [comment]
@loftusa #752 pls check this PR

**Pull request closed without merging**
