### PR TITLE
Fix to ensure reproducibility of `inference.latent_distribution_test`

### LINKED ISSUE #775: Make LDT reproducible
## Is your feature request related to a problem? Please describe.
Latent distribution test currently does not give reproducible results

## Describe the solution you'd like
Modification of LDT code to ensure that it gives reproducible results

## Provide references (if applicable)
See #744

### PR DESCRIPTION
**Pull request by kareef928**
#### Reference Issues/PRs
Fixes #775 

#### What does this implement/fix? Briefly explain your changes.
Ensures that all returns of LDT are reproducible

### CODE REVIEW

**Comment by kareef928** [comment]
@bdpedigo im guessing that these tests will not be fixed until the new version of hyppo is released, right?

**Comment by bdpedigo** [comment]
> @bdpedigo im guessing that these tests will not be fixed until the new version of hyppo is released, right?

if i understand you, yes.

can you ask Sambit about timing for that release? also, you'll have to update the version spec for Hyppo in graspologic. do you know how to do so? lmk if not and I'll show you

**Comment by bdpedigo** [comment]
@kareef928 looks like hyppo was released so lets see if this works now? I just started the tests

**Comment by bdpedigo** [comment]
@kareef928 looks like there are still some errors to track down here before we can merge

**Review by bdpedigo — APPROVED** [review]

**Pull request merged**
