### PR TITLE
Adds option to use numpy.random.Generator object to sample_edges

### LINKED ISSUE #603: Add option to utilize numpy.random.Generator object in sample_edges
## Issue:
 Sample_edges utilizes numpy.random.RandomState, would be nice to be able to utilize a numpy.random.Generator object as well. 

## Solution:
Add option input to sample_edges that accepts a numpy.random.Generator object. If this input is provided then sample_edges should use the numpy.random.Generator object to sample from bernoulli. 

## References
[numpy.random.Generator](https://numpy.org/doc/stable/reference/random/index.html?highlight=random%20sampling%20numpy%20random#module-numpy.random) is the newly adopted pseudo-random number generator utilized and maintained by numpy. Check out [here](https://numpy.org/doc/stable/reference/random/legacy.html#numpy.random.RandomState) in the numpy doc the compatibility guarantee for numpy.random.RandomState which is what is currently being used.

### PR DESCRIPTION
**Pull request by PerifanosPrometheus**
#### Reference Issues/PRs

Closes #603 

#### What does this implement/fix? Briefly explain your changes.

Adds input to sample_edges in simulations.py so that if desired [numpy random Generator](https://numpy.org/doc/stable/reference/random/generator.html) can be used rather than [numpy RandomState](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.random.html) which is outdated and no longer mantained

### CODE REVIEW

**Comment by bdpedigo** [comment]
@tliu68 I'm wondering if you might have time to review this (small PR)?

**Comment by tliu68** [comment]
> @tliu68 I'm wondering if you might have time to review this (small PR)?

Of course!

**Comment by PerifanosPrometheus** [comment]
@tliu68 The changes on the modularity file have nothing to do with the PR but for some reason are showing up. I am not sure what happened with that file but it is just a tab difference which I can change anytime

**Comment by tliu68** [comment]
> @tliu68 The changes on the modularity file have nothing to do with the PR but for some reason are showing up. I am not sure what happened with that file but it is just a tab difference which I can change anytime

There might an accident change in the first commit? I see that you tried to fix it in the second commit, but it does not seem to be changing it back to what it was before, which is causing the conflict. I think it needs to be resolved first.

**Comment by PerifanosPrometheus** [comment]
> > @tliu68 The changes on the modularity file have nothing to do with the PR but for some reason are showing up. I am not sure what happened with that file but it is just a tab difference which I can change anytime
> 
> There might an accident change in the first commit? I see that you tried to fix it in the second commit, but it does not seem to be changing it back to what it was before, which is causing the conflict. I think it needs to be resolved first.

I think it was just an accidental change. Basically, in the first commit the check was showing that the difference was a tab, so I removed it and now it seems to be the opposite. 

Will definitely fix it though

**Comment by PerifanosPrometheus** [comment]
@tliu68 Fixed accidental changes on modularity.py. I think it was a bug, as I had to push the fix a couple of times before it realized the file was unchanged.

**Comment by dwaynepryce** [comment]
> @tliu68 Fixed accidental changes on modularity.py. I think it was a bug, as I had to push the fix a couple of times before it realized the file was unchanged.

This was not a bug!  Or rather, nothing you did incorrectly - someone submitted a PR to fix one of the modularity docstrings and I managed a god merge even though they committed it with `\t` instead of `   `.  This merged to dev, then you got it, and since you were not a monster and actually looked at whether `graspologic CI / code-format-check` was green or not, YOU got stuck with _my_ mistake.  Mea culpa!  You're not crazy, I'm just a jerk and I'm sorry :(

**Comment by PerifanosPrometheus** [comment]
> > @tliu68 Fixed accidental changes on modularity.py. I think it was a bug, as I had to push the fix a couple of times before it realized the file was unchanged.
> 
> This was not a bug! Or rather, nothing you did incorrectly - someone submitted a PR to fix one of the modularity docstrings and I managed a god merge even though they committed it with `\t` instead of ` `. This merged to dev, then you got it, and since you were not a monster and actually looked at whether `graspologic CI / code-format-check` was green or not, YOU got stuck with _my_ mistake. Mea culpa! You're not crazy, I'm just a jerk and I'm sorry :(

Thanks for the info and don't worry I had imagined something was going on in the background : )

**Comment by tliu68** [comment]
Looks good to me. Just curious are you planning to change RandomState to Generator in other methods that call `sample_edhes` (e.g., `rdpg`) apart from `mmsbm`? 
And @bdpedigo are we planning to make such substitution in other functions/methods that are relevant?

**Comment by bdpedigo** [comment]
i feel like we should, otherwise there is not much point. not sure if it should be in this PR or not, thoughts?

**Comment by tliu68** [comment]
> i feel like we should, otherwise there is not much point. not sure if it should be in this PR or not, thoughts?

Agreed. But not sure what @PerifanosPrometheus's plan for this PR is

**Comment by PerifanosPrometheus** [comment]
@bdpedigo @tliu68 Apologies for the late reply, I somehow missed the notification. I can certainly run through all the simulations.py and perform the change. This will probably involve also changing all the tutorials, but I am totally up for it.

**Comment by bdpedigo** [comment]
closing as stale, but happy to reopen if someone wants to add this rng compatibility to the rest of `simulations`

**Pull request closed without merging**
