### PR TITLE
add NotImplementedError to fit_transform in MultipleASE and OmnibusEmbed

### LINKED ISSUE #797: [BUG] MultipleASE and OmnibusEmbed mistakenly have a .transform method
## Expected Behavior
We never tested or intended the out of sample transform to work for those multiple graph embeddings as the inputs wouldn't even make sense

## Additional Details
- Either of these classes _could_ have a transform method if someone wants to implement it and go through the math
- For now, I recommend that we just override this method in the `BaseEmbedMulti` class and have them raise a not implemented error

### PR DESCRIPTION
**Pull request by sneznaj**
Fixes #797

### CODE REVIEW

**Comment by bdpedigo** [comment]
@loftusa wondering if you'd have time to review this? LMK either way

**Comment by bdpedigo** [comment]
@sneznaj thanks for the PR! We'll get back to you soon.

**Comment by loftusa** [comment]
Hi @sneznaj

I think we wanted the change to override `transform` in `BaseEmbedMulti`, rather than on MASE and OMNI individually.

The docstring text also shouldn't just say "not implemented". Maybe add something to the notes section of the docstring for MASE and OMNI explaining that out-of-sample transformations are not implemented for multiple-graph embeddings.

Also see comment here: https://github.com/microsoft/graspologic/issues/797#issuecomment-970572572

**Comment by bdpedigo** [comment]
Going to close for now since there hasn't been any activity, but more than happy to reopen if someone wants to take this back up!

**Pull request closed without merging**
