### PR TITLE
Intersphinx woes

### PR DESCRIPTION
**Pull request by bdpedigo**
#### What does this implement/fix? Explain your changes.
Fixes `build_documentation` errors that somehow popped up on all open PRs.

Also fixed some warnings from intersphinx while I was at it related to `.inv` files of other libraries moving.

#### Any other comments?
I do not question the will of the intersphinx gods

### CODE REVIEW

**Comment by bdpedigo** [comment]
@dwaynepryce the error that this fixes is now holding up other PRs like #510. I think this fixes it?

**Review by dwaynepryce — APPROVED** [review]

**Comment by dwaynepryce** [comment]
I think that last error on #510 was just a temporary thing.  If you read those and it sounds like a timeout, it's always worth just trying to rerun the GH actions and see if that fixes it.

It looks like I can trigger a rerun of things just by clicking the `Re-run all jobs` button on the Actions page (you should be able to too, I think?) and that will let us know in the future if that's the problem.

I'm not entirely convinced I know what's going on here but sphinx is dark magicks and I don't see anything in here that raises any alarms.  I just wish I knew why we had to do this in the first place :|

**Comment by bdpedigo** [comment]
hmm i was confused because I saw that same issue on multiple PRs so I didnt think it was just a single timeout issue

**Comment by dwaynepryce** [comment]
Maybe you're right, but it also did work on #510 at least once so I expected it was a transient thing.

**Review by dwaynepryce — APPROVED** [review]

**Pull request merged**
